config/routes.rb
Rails.application.routes.draw do
  # get 'book_comments/create'
  # get 'book_comments/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

   devise_for :users

  root to: "homes#top"
  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorite, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do
    # フォロー機能用のルーティングを追加
    resource :relationships, only: [:create, :destroy]
    #フォローしている人の一覧ページへのルーティング
    get :follows, on: :member
    # フォローしてくれている人の一覧ページへのルーティング
    get :followers, on: :member
  end

  get 'search' => "searches#search"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy


  # ============フォローする・している側からの視点==========
  # フォローする側の情報についての紐づけ
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  # activeを通して、フォローされる人の情報を取得する⇒source:followerになる
  has_many :followings, through: :active_relationships, source: :followed

  # # ========================================================

  # # ==========フォロワー側の視点・フォローされる方================================
  # Railsの命名規則の観点から、followed→followers(単数形⇒複数形)として認識してくれる
  # フォローされる側の情報についての紐付け
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :followed_id, dependent: :destroy
  # passiveを通して、フォローしてくるユーザー情報を取得⇒source: :followingになる
  has_many :followers, through: :passive_relationships, source: :following


  #画像をUserモデルで取り扱う
  has_one_attached :profile_image

  #validate機能：空欄や文字制限を設ける
  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }



  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  def followed_by?(user)
    # 今自分が(引数のユーザー)がフォローしようとしているユーザー(受け側)がフォローしているかどうかを判別する
    passive_relationships.find_by(following_id: user.id).present?
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
        @user = User.where("name LIKE?", "#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?", "%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update, :edit]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

# ==============追加================
  def follows
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end
# ==============追加================

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user.id)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数:
          <%= user.followings.count %>
        </td>
        <td>フォロワー数:
          <%= user.followers.count %>
        </td>

        <td>
          <!--フォローボタンを挿入-->
          <!--ログインしているユーザーが引数で渡されているユーザー(つまり、一覧のそれぞれのユーザー-->
          <!--とイコールかどうか確認するIf文⇒自分のユーザー箇所ではボタンは表示されないようにする-->
          <% if current_user != user %>
            <% if user.followed_by?(current_user) %>
              <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
            <% else %>
              <%= link_to "フォローする", user_relationships_path(user.id), method: :create %>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user %></td>


      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <!--フォロー/フォロワー機能を挿入する-->
  <!--フォロー人数の表示-->
  <tr>
    <th>follows</th>
    <th><%= link_to user.followings.count, follows_user_path(user.id) %></th>
  </tr>
  <!--フォロワー人数の表示-->
  <tr>
    <th>followers</th>
    <th><%= link_to user.followers.count, followers_user_path(user.id) %></th>
  </tr>
</table>
  <div>
    <% if current_user != user %>
      <% if user.followed_by?(current_user) %>
        <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: 'btn btn-info' %>
      <% else %>
        <%= link_to "フォローする", user_relationships_path(user.id), method: :create, class: 'btn btn-success' %>
      <% end %>
    <% end %>
  </div>

<div class='row'>
  <% if current_user == user %>
  <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit "Update User", class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<h1>Follower Users</h1>


<div class="container-fluid">


<table class="table table-striped">
 <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数：
          <%= user.followings.count %>
        </td>
        <td>フォロワー数：
          <%= user.followers.count %>
        </td>

        <td>
          <!--フォローボタンを挿入-->
          <!--ログインしているユーザーが引数で渡されているユーザー(つまり、一覧のそれぞれのユーザー-->
          <!--とイコールかどうか確認するIf文⇒自分のユーザー箇所ではボタンは表示されないようにする-->
          <% if current_user != user %>
            <% if user.followed_by?(current_user) %>
              <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
            <% else %>
              <%= link_to "フォローする", user_relationships_path(user.id), method: :create %>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user_path(user.id) %></td>
      </tr>

    <% end %>
  </tbody>
</table>

</div>

app/views/users/follows.html.erb
<h1>Follows Users</h1>

<div class="container-fluid">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数：<%= user.followings.count %></td>
        <td>フォロワー数：<%= user.followers.count %></td>
        <td><%= link_to "Show", user_path(user.id) %></td>
      </tr>
      <% end %>
    </tbody>

  </table>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>

    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>

    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= render 'index',users: @users %>
    </div>

  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>