config/routes.rb
Rails.application.routes.draw do
  # get 'book_comments/create'
  # get 'book_comments/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

   devise_for :users

  root to: "homes#top"
  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorite, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do
    # フォロー機能用のルーティングを追加
    resource :relationships, only: [:create, :destroy]
    #フォローしている人の一覧ページへのルーティング
    get :follows, on: :member
    # フォローしてくれている人の一覧ページへのルーティング
    get :followers, on: :member
  end

  get 'search' => "searches#search"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def search
    @range = params[:range]
    @word = params[:word]

    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @books = Book.looks(params[:search], params[:word])
    end
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/search.html.erb
<div class="container">
  <table class="table">
    <!--検索対象モデルがUserの時-->
  <% if @range == "User" %>
  <h2>Users search for "<%= @word %>"</h2>
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3">introduction</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td>
            <%= link_to user_path(user.id) do %>
            <%= image_tag user.get_profile_image, size: '50x50' %>
            <% end %>
          </td>
          <td>
            <%= link_to user_path(user.id) do %>
            <%= user.name %>
            <% end %>
          </td>
          <td><%= user.introduction %></td>
        </tr>
      <% end %>
    </tbody>
    <% else %>
    <!--検索対象がbookの時-->
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
        </tr>
      </thead>
      <tbody>
        <h2>Books search for "<%= @word %>"</h2>
        <% @books.each do |book| %>
        <tr>
          <td>
            <%= link_to user_path(book.user) do %>
            <%= image_tag book.user.get_profile_image, size: '50x50' %>
            <% end %>
          </td>
          <td>
            <%= link_to book_path(book.id) do %>
            <%= book.title %>
            <% end %>
            </td>
          <td><%= book.body %></td>
        </tr>
        <% end %>
      </tbody>
    <% end %>
    </table>
</div>